spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: xjl011025
  application:
    name: nacos-payment-order
  cloud:
    nacos:
      discovery:
        # 换成nginx的1111端口，做集群
        server-addr: 124.223.182.14:1111
#        server-addr: localhost:8848 #配置Nacos地址


  redis:
    host: 124.223.182.14
    port: 6399
    database: 0
    password: xjl2550908862xjl011025.
#    cluster:
#      #设置key的生存时间，当key过期时，它会被自动删除；
#      expire-seconds: 120
#      #设置命令的执行时间，如果超过这个时间，则报错;
#      command-timeout: 5000
      #设置redis集群的节点信息
#      nodes: 124.223.182.14:6398,124.223.182.14:6397,124.223.182.14:6396,124.223.182.14:6395,124.223.182.14:6394,124.223.182.14:6393
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mvc:
    static-path-pattern: static/**
    view:
      prefix: /WEB-INF/
      suffix: .jsp


  main:
    allow-circular-references: true

  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: false
server:
  port: 83

management:
  endpoints:
    web:
      exposure:
        include: '*'


#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://cloud-gateway

#mybatis-plus开启二级缓存
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled:
      true
# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
